version: '3.1'
  
volumes: 
  squash-tm-bundles:
  squash-tm-logs:
  squash-tm-plugins:
  squash-tm-db:
  squash-tm-conf:

services:
  squash-tm-mdb:
    image: mariadb:10.2
    container_name: squash-tm-mdb
    # restart: always
    volumes: 
    - squash-tm-db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: squashtm
      MYSQL_USER: user
      MYSQL_PASSWORD: Passw0rd
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    command :
      - '--sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES'
      - '--character-set-server=utf8' 
      - '--collation-server=utf8_bin'

  squash-tm:
    container_name: squash-tm
    depends_on:
      - squash-tm-mdb
    environment:
      DB_TYPE: mysql
      DB_HOST: squash-tm-mdb
      DB_PORT: 3306
      DB_NAME: squashtm
      DB_USERNAME: user
      DB_PASSWORD: Passw0rd
    ports:
    - 8099:8080/tcp
    image: canecas/squash-tm
    volumes:
    - squash-tm-bundles:/etc/squash-tm/bundles
    - squash-tm-logs:/etc/squash-tm/logs
    - squash-tm-plugins:/etc/squash-tm/plugins
    - squash-tm-conf:/etc/squash-tm/conf
